'use strict'

/*
|--------------------------------------------------------------------------
| TipeKendaraanSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const TipeKendaraan = use('App/Models/TipeKendaraan')
class TipeKendaraanSeeder {
  async run () {
    const data = [
      { id_merk_kendaraan: 1, tipe_kendaraan: '86'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Agya'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Alphard'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Avanza'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Calya'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Camry'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'CHR'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Corolla'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Corolla Cross All New'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Dyna'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Fortuner All New'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Hiace'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Hilux'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Innova All New'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Land Cruiser'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Rush All New'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Sienta'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Supra'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Vellfire'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Vios'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Voxy'},
      { id_merk_kendaraan: 1, tipe_kendaraan: 'Yaris'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'City'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'Civic'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'CRV'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'HRV'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'Jazz'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'Mobilio'},
      { id_merk_kendaraan: 2, tipe_kendaraan: 'Odyssey'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Ayla'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Gran Max BV'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Gran Max Minibus'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Gran Max PU'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Hi-MAX'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Luxio'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Sigra'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Sirion'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Terios All New'},
      { id_merk_kendaraan: 3, tipe_kendaraan: 'Xenia'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'APV'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Baleno'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Carry'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Ertiga'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Grand Vitara'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Ignis'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Jimny'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'Karimun Wagon R'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'SX4'},
      { id_merk_kendaraan: 4, tipe_kendaraan: 'XL7'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Elgrand'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Juke'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Livina'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'March'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'NP 300 Navara'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Serena'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Teana'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'Terra'},
      { id_merk_kendaraan: 5, tipe_kendaraan: 'X-Trail'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Colt Diesel'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Colt L300'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Colt T120SS'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Delica'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Eclipse Cross'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Fuso'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Outlander Sport'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Pajero Sport'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Strada Triton'},
      { id_merk_kendaraan: 6, tipe_kendaraan: 'Xpander'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'A4'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'A5'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'A6'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'A8'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'Q3'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'Q5'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'Q7'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'R8'},
      { id_merk_kendaraan: 7, tipe_kendaraan: 'TT'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'i3s'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'i8'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 3'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 4'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 5'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 6'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 7'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri 8'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri M'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X1'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X2'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X3'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X4'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X5'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X6'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri X7'},
      { id_merk_kendaraan: 8, tipe_kendaraan: 'Seri Z'},
      { id_merk_kendaraan: 9, tipe_kendaraan: 'Colorado'},
      { id_merk_kendaraan: 9, tipe_kendaraan: 'Spark'},
      { id_merk_kendaraan: 9, tipe_kendaraan: 'Trailblazer'},
      { id_merk_kendaraan: 9, tipe_kendaraan: 'Trax'},
      { id_merk_kendaraan: 10, tipe_kendaraan: 'Cross'},
      { id_merk_kendaraan: 10, tipe_kendaraan: 'GO'},
      { id_merk_kendaraan: 10, tipe_kendaraan: 'GO+'},
      { id_merk_kendaraan: 11, tipe_kendaraan: 'Glory 560'},
      { id_merk_kendaraan: 11, tipe_kendaraan: 'Glory 580'},
      { id_merk_kendaraan: 11, tipe_kendaraan: 'Supercab'},
      { id_merk_kendaraan: 12, tipe_kendaraan: 'Dutro 300'},
      { id_merk_kendaraan: 12, tipe_kendaraan: 'Hino BUS'},
      { id_merk_kendaraan: 12, tipe_kendaraan: 'Ranger 500'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'H1'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'i10'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'i20'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'Kona'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'Santa Fe'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'Starex Mover'},
      { id_merk_kendaraan: 13, tipe_kendaraan: 'Tucson'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'D-Max'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'ELF'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'Giga'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'MU-X'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'Panther'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'Pick Up'},
      { id_merk_kendaraan: 14, tipe_kendaraan: 'Traga'},
      { id_merk_kendaraan: 15, tipe_kendaraan: 'F-Pace'},
      { id_merk_kendaraan: 15, tipe_kendaraan: 'XF'},
      { id_merk_kendaraan: 15, tipe_kendaraan: 'XJ'},
      { id_merk_kendaraan: 16, tipe_kendaraan: 'Cherokee'},
      { id_merk_kendaraan: 16, tipe_kendaraan: 'Compass'},
      { id_merk_kendaraan: 16, tipe_kendaraan: 'Wrangler'},
      { id_merk_kendaraan: 17, tipe_kendaraan: 'All New Seltos'},
      { id_merk_kendaraan: 17, tipe_kendaraan: 'K2700'},
      { id_merk_kendaraan: 17, tipe_kendaraan: 'Picanto'},
      { id_merk_kendaraan: 17, tipe_kendaraan: 'Rio'},
      { id_merk_kendaraan: 17, tipe_kendaraan: 'Sedona'},
      { id_merk_kendaraan: 18, tipe_kendaraan: 'Discovery Sport'},
      { id_merk_kendaraan: 18, tipe_kendaraan: 'Range Rover Evoque'},
      { id_merk_kendaraan: 18, tipe_kendaraan: 'Range Rover Sport'},
      { id_merk_kendaraan: 18, tipe_kendaraan: 'Range Rover Velar'},
      { id_merk_kendaraan: 19, tipe_kendaraan: 'ES'},
      { id_merk_kendaraan: 19, tipe_kendaraan: 'LC'},
      { id_merk_kendaraan: 19, tipe_kendaraan: 'LX'},
      { id_merk_kendaraan: 19, tipe_kendaraan: 'NX'},
      { id_merk_kendaraan: 19, tipe_kendaraan: 'RX'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda 2 Hatchback'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda 3 Hatchback'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda 3 Sedan'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda 6 Estate'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda 6 Sedan'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda CX-5'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda CX-8'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda CX-9'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'Mazda CX30'},
      { id_merk_kendaraan: 20, tipe_kendaraan: 'New Mazda CX-3'}
    ]

    await TipeKendaraan.createMany(data)
  }
}

module.exports = TipeKendaraanSeeder
